-- CarFix schema based on db'.sql + extensions for app logic
-- Create/recreate database outside this script (see setup_db.ps1)

BEGIN;

CREATE TABLE IF NOT EXISTS public."Roles"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Statuses"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Statuses" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Suppliers"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Phone" text NOT NULL,
    CONSTRAINT "PK_Suppliers" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Services"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text,
    "Price" numeric NOT NULL,
    CONSTRAINT "PK_Services" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Users"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Login" text NOT NULL,
    "Password" text NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Roles" FOREIGN KEY ("RoleId") REFERENCES public."Roles"("Id")
);

CREATE TABLE IF NOT EXISTS public."Cars"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "VIN" text NOT NULL,
    "Brand" text NOT NULL,
    "Model" text NOT NULL,
    "Year" integer NOT NULL,
    "PlateNumber" text NOT NULL,
    "Mileage" integer NOT NULL,
    "ClientId" integer NOT NULL,
    CONSTRAINT "PK_Cars" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Cars_Users" FOREIGN KEY ("ClientId") REFERENCES public."Users"("Id")
);

CREATE TABLE IF NOT EXISTS public."Orders"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "DateCreated" timestamp with time zone NOT NULL,
    "DateFinished" timestamp with time zone,
    "StatusId" integer NOT NULL,
    "AutomobileId" integer NOT NULL,
    "MechanicId" integer NOT NULL,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Orders_Statuses" FOREIGN KEY ("StatusId") REFERENCES public."Statuses"("Id"),
    CONSTRAINT "FK_Orders_Cars" FOREIGN KEY ("AutomobileId") REFERENCES public."Cars"("Id"),
    CONSTRAINT "FK_Orders_Users" FOREIGN KEY ("MechanicId") REFERENCES public."Users"("Id")
);

CREATE TABLE IF NOT EXISTS public."Comments"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "Text" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsFinalClientReview" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_Comments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Comments_Orders" FOREIGN KEY ("OrderId") REFERENCES public."Orders"("Id")
);

CREATE TABLE IF NOT EXISTS public."Parts"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Article" text NOT NULL,
    "Name" text NOT NULL,
    "Quantity" integer NOT NULL,
    "PurchasePrice" numeric NOT NULL,
    "SalePrice" numeric NOT NULL,
    "SupplierId" integer NOT NULL,
    CONSTRAINT "PK_Parts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Parts_Suppliers" FOREIGN KEY ("SupplierId") REFERENCES public."Suppliers"("Id")
);

CREATE TABLE IF NOT EXISTS public."OrderParts"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "PartId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    CONSTRAINT "PK_OrderParts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrderParts_Orders" FOREIGN KEY ("OrderId") REFERENCES public."Orders"("Id"),
    CONSTRAINT "FK_OrderParts_Parts" FOREIGN KEY ("PartId") REFERENCES public."Parts"("Id")
);

CREATE TABLE IF NOT EXISTS public."OrderServices"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "ServiceId" integer NOT NULL,
    "ActualPrice" numeric NOT NULL,
    "IsCompleted" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_OrderServices" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrderServices_Orders" FOREIGN KEY ("OrderId") REFERENCES public."Orders"("Id"),
    CONSTRAINT "FK_OrderServices_Services" FOREIGN KEY ("ServiceId") REFERENCES public."Services"("Id")
);

CREATE TABLE IF NOT EXISTS public."Payments"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "Amount" numeric NOT NULL,
    "Method" text NOT NULL,
    CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Payments_Orders" FOREIGN KEY ("OrderId") REFERENCES public."Orders"("Id")
);

CREATE TABLE IF NOT EXISTS public."Shifts"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "DayOfWeek" text NOT NULL,
    "UserId" integer,
    CONSTRAINT "PK_Shifts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Shifts_Users" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public."UserServices"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ServiceId" integer NOT NULL,
    CONSTRAINT "PK_UserServices" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserServices_Users" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id"),
    CONSTRAINT "FK_UserServices_Services" FOREIGN KEY ("ServiceId") REFERENCES public."Services"("Id")
);

CREATE TABLE IF NOT EXISTS public."PartRequests"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ItemName" text NOT NULL,
    "Quantity" integer NOT NULL,
    "Note" text NOT NULL DEFAULT '',
    "UserId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PartRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PartRequests_Users" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id")
);

INSERT INTO public."Roles" ("Id", "Name") OVERRIDING SYSTEM VALUE VALUES
(1, 'Admin'),
(2, 'Mechanic'),
(3, 'Manager'),
(4, 'Client');

INSERT INTO public."Statuses" ("Id", "Name") OVERRIDING SYSTEM VALUE VALUES
(1, 'Новый'),
(2, 'В работе'),
(3, 'Завершен'),
(4, 'Отменен');

INSERT INTO public."Users" ("Id", "Name", "Login", "Password", "RoleId") OVERRIDING SYSTEM VALUE VALUES
(1, 'Админ Иванов', 'admin', 'admin', 1),
(2, 'Механик Петров', 'mech1', 'mech1', 2),
(3, 'Механик Сидоров', 'mech2', 'mech2', 2),
(4, 'Менеджер Козлова', 'manager', 'manager', 3),
(5, 'Клиент Орлов', 'client1', 'client1', 4),
(6, 'Клиент Волкова', 'client2', 'client2', 4);

INSERT INTO public."Services" ("Id", "Name", "Description", "Price") OVERRIDING SYSTEM VALUE VALUES
(1, 'Замена масла', 'Замена моторного масла и фильтра', 2500),
(2, 'Диагностика', 'Компьютерная диагностика', 1500),
(3, 'Замена колодок', 'Замена тормозных колодок', 4000),
(4, 'Шиномонтаж', 'Снятие/установка и балансировка', 2000);

INSERT INTO public."UserServices" ("Id", "UserId", "ServiceId") OVERRIDING SYSTEM VALUE VALUES
(1, 2, 1),
(2, 2, 2),
(3, 2, 3),
(4, 3, 2),
(5, 3, 4);

INSERT INTO public."Suppliers" ("Id", "Name", "Phone") OVERRIDING SYSTEM VALUE VALUES
(1, 'АвтоДеталь', '+7-900-111-22-33'),
(2, 'ЗапЧастьПро', '+7-900-444-55-66');

INSERT INTO public."Parts" ("Id", "Article", "Name", "Quantity", "PurchasePrice", "SalePrice", "SupplierId") OVERRIDING SYSTEM VALUE VALUES
(1, 'OIL-5W30', 'Масло 5W-30', 20, 800, 1200, 1),
(2, 'FLT-001', 'Масляный фильтр', 15, 300, 500, 1),
(3, 'BRK-FR', 'Колодки передние', 8, 1500, 2500, 2),
(4, 'TIRE-R', 'Ремкомплект шины', 2, 400, 700, 2);

INSERT INTO public."Cars" ("Id", "VIN", "Brand", "Model", "Year", "PlateNumber", "Mileage", "ClientId") OVERRIDING SYSTEM VALUE VALUES
(1, 'XTA21703000000001', 'Lada', 'Vesta', 2020, 'A123BC777', 45000, 5),
(2, 'XTA21703000000002', 'Toyota', 'Camry', 2018, 'B456DE199', 98000, 6);

INSERT INTO public."Orders" ("Id", "DateCreated", "DateFinished", "StatusId", "AutomobileId", "MechanicId") OVERRIDING SYSTEM VALUE VALUES
(1, TIMESTAMPTZ '2026-10-06 09:00:00+03', NULL, 2, 1, 2),
(2, TIMESTAMPTZ '2026-10-07 14:00:00+03', NULL, 1, 2, 3),
(3, TIMESTAMPTZ '2026-10-01 10:00:00+03', TIMESTAMPTZ '2026-10-01 16:00:00+03', 3, 1, 2);

INSERT INTO public."OrderServices" ("Id", "OrderId", "ServiceId", "ActualPrice", "IsCompleted") OVERRIDING SYSTEM VALUE VALUES
(1, 1, 1, 2500, false),
(2, 1, 2, 1500, false),
(3, 2, 4, 2000, false),
(4, 3, 3, 4000, true);

INSERT INTO public."OrderParts" ("Id", "OrderId", "PartId", "Quantity") OVERRIDING SYSTEM VALUE VALUES
(1, 1, 1, 4),
(2, 1, 2, 1),
(3, 3, 3, 1);

INSERT INTO public."Payments" ("Id", "OrderId", "Amount", "Method") OVERRIDING SYSTEM VALUE VALUES
(1, 3, 6500, 'Карта'),
(2, 1, 2000, 'Наличные');

INSERT INTO public."Comments" ("Id", "OrderId", "Text", "CreatedAt", "IsFinalClientReview") OVERRIDING SYSTEM VALUE VALUES
(1, 1, 'Нужна проверка уровня масла', TIMESTAMPTZ '2026-10-06 10:00:00+03', false),
(2, 3, 'Отличный сервис, спасибо!', TIMESTAMPTZ '2026-10-01 17:00:00+03', true);

INSERT INTO public."Shifts" ("Id", "Name", "DayOfWeek", "UserId") OVERRIDING SYSTEM VALUE VALUES
(1, 'Утро', 'Пн', 2),
(2, 'Вечер', 'Пн', 3),
(3, 'Утро', 'Вт', 2),
(4, 'Вечер', 'Вт', 3),
(5, 'Утро', 'Ср', 3),
(6, 'Вечер', 'Ср', 2),
(7, 'Утро', 'Чт', 2),
(8, 'Вечер', 'Чт', 3),
(9, 'Утро', 'Пт', 3),
(10, 'Вечер', 'Пт', 2);

SELECT setval(pg_get_serial_sequence('public."Roles"', 'Id'), (SELECT MAX("Id") FROM public."Roles"));
SELECT setval(pg_get_serial_sequence('public."Statuses"', 'Id'), (SELECT MAX("Id") FROM public."Statuses"));
SELECT setval(pg_get_serial_sequence('public."Users"', 'Id'), (SELECT MAX("Id") FROM public."Users"));
SELECT setval(pg_get_serial_sequence('public."Services"', 'Id'), (SELECT MAX("Id") FROM public."Services"));
SELECT setval(pg_get_serial_sequence('public."UserServices"', 'Id'), (SELECT MAX("Id") FROM public."UserServices"));
SELECT setval(pg_get_serial_sequence('public."Suppliers"', 'Id'), (SELECT MAX("Id") FROM public."Suppliers"));
SELECT setval(pg_get_serial_sequence('public."Parts"', 'Id'), (SELECT MAX("Id") FROM public."Parts"));
SELECT setval(pg_get_serial_sequence('public."Cars"', 'Id'), (SELECT MAX("Id") FROM public."Cars"));
SELECT setval(pg_get_serial_sequence('public."Orders"', 'Id'), (SELECT MAX("Id") FROM public."Orders"));
SELECT setval(pg_get_serial_sequence('public."OrderServices"', 'Id'), (SELECT MAX("Id") FROM public."OrderServices"));
SELECT setval(pg_get_serial_sequence('public."OrderParts"', 'Id'), (SELECT MAX("Id") FROM public."OrderParts"));
SELECT setval(pg_get_serial_sequence('public."Payments"', 'Id'), (SELECT MAX("Id") FROM public."Payments"));
SELECT setval(pg_get_serial_sequence('public."Comments"', 'Id'), (SELECT MAX("Id") FROM public."Comments"));
SELECT setval(pg_get_serial_sequence('public."Shifts"', 'Id'), (SELECT MAX("Id") FROM public."Shifts"));

COMMIT;
