-- CarFix schema + ~20 rows per main table
BEGIN;

DROP TABLE IF EXISTS public."PartRequests" CASCADE;
DROP TABLE IF EXISTS public."Comments" CASCADE;
DROP TABLE IF EXISTS public."Payments" CASCADE;
DROP TABLE IF EXISTS public."OrderParts" CASCADE;
DROP TABLE IF EXISTS public."OrderServices" CASCADE;
DROP TABLE IF EXISTS public."Orders" CASCADE;
DROP TABLE IF EXISTS public."UserServices" CASCADE;
DROP TABLE IF EXISTS public."Shifts" CASCADE;
DROP TABLE IF EXISTS public."Parts" CASCADE;
DROP TABLE IF EXISTS public."Cars" CASCADE;
DROP TABLE IF EXISTS public."Users" CASCADE;
DROP TABLE IF EXISTS public."Services" CASCADE;
DROP TABLE IF EXISTS public."Suppliers" CASCADE;
DROP TABLE IF EXISTS public."Statuses" CASCADE;
DROP TABLE IF EXISTS public."Roles" CASCADE;

CREATE TABLE public."Roles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL
);

CREATE TABLE public."Statuses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL
);

CREATE TABLE public."Suppliers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL,
    "Phone" text NOT NULL
);

CREATE TABLE public."Services" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL,
    "Description" text,
    "Price" numeric NOT NULL
);

CREATE TABLE public."Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL,
    "Login" text NOT NULL,
    "Password" text NOT NULL,
    "RoleId" integer NOT NULL REFERENCES public."Roles"("Id")
);

CREATE TABLE public."Cars" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "VIN" text NOT NULL,
    "Brand" text NOT NULL,
    "Model" text NOT NULL,
    "Year" integer NOT NULL,
    "PlateNumber" text NOT NULL,
    "Mileage" integer NOT NULL,
    "ClientId" integer NOT NULL REFERENCES public."Users"("Id")
);

CREATE TABLE public."Orders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DateCreated" timestamptz NOT NULL,
    "DateFinished" timestamptz,
    "StatusId" integer NOT NULL REFERENCES public."Statuses"("Id"),
    "AutomobileId" integer NOT NULL REFERENCES public."Cars"("Id"),
    "MechanicId" integer NOT NULL REFERENCES public."Users"("Id")
);

CREATE TABLE public."Comments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OrderId" integer NOT NULL REFERENCES public."Orders"("Id"),
    "Text" text NOT NULL,
    "CreatedAt" timestamptz NOT NULL,
    "IsFinalClientReview" boolean NOT NULL DEFAULT false
);

CREATE TABLE public."Parts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Article" text NOT NULL,
    "Name" text NOT NULL,
    "Quantity" integer NOT NULL,
    "PurchasePrice" numeric NOT NULL,
    "SalePrice" numeric NOT NULL,
    "SupplierId" integer NOT NULL REFERENCES public."Suppliers"("Id")
);

CREATE TABLE public."OrderParts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OrderId" integer NOT NULL REFERENCES public."Orders"("Id"),
    "PartId" integer NOT NULL REFERENCES public."Parts"("Id"),
    "Quantity" integer NOT NULL
);

CREATE TABLE public."OrderServices" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OrderId" integer NOT NULL REFERENCES public."Orders"("Id"),
    "ServiceId" integer NOT NULL REFERENCES public."Services"("Id"),
    "ActualPrice" numeric NOT NULL,
    "IsCompleted" boolean NOT NULL DEFAULT false
);

CREATE TABLE public."Payments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OrderId" integer NOT NULL REFERENCES public."Orders"("Id"),
    "Amount" numeric NOT NULL,
    "Method" text NOT NULL
);

CREATE TABLE public."Shifts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL,
    "DayOfWeek" text NOT NULL,
    "UserId" integer REFERENCES public."Users"("Id") ON DELETE SET NULL
);

CREATE TABLE public."UserServices" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL REFERENCES public."Users"("Id"),
    "ServiceId" integer NOT NULL REFERENCES public."Services"("Id")
);

CREATE TABLE public."PartRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemName" text NOT NULL,
    "Quantity" integer NOT NULL,
    "Note" text NOT NULL DEFAULT '',
    "UserId" integer NOT NULL REFERENCES public."Users"("Id"),
    "CreatedAt" timestamptz NOT NULL
);

INSERT INTO public."Roles" ("Id", "Name") OVERRIDING SYSTEM VALUE VALUES
(1,'Admin'),(2,'Mechanic'),(3,'Manager'),(4,'Client');

INSERT INTO public."Statuses" ("Id", "Name") OVERRIDING SYSTEM VALUE VALUES
(1,'Новый'),(2,'В работе'),(3,'Завершен'),(4,'Отменен');

INSERT INTO public."Users" ("Id","Name","Login","Password","RoleId") OVERRIDING SYSTEM VALUE VALUES
(1,'Админ Иванов','admin','admin',1),
(2,'Менеджер Козлова','manager','manager',3),
(3,'Менеджер Смирнов','manager2','manager2',3),
(4,'Механик Петров','mech1','mech1',2),
(5,'Механик Сидоров','mech2','mech2',2),
(6,'Механик Орлов','mech3','mech3',2),
(7,'Механик Волков','mech4','mech4',2),
(8,'Механик Соколов','mech5','mech5',2),
(9,'Клиент Алексеев','client1','client1',4),
(10,'Клиент Борисова','client2','client2',4),
(11,'Клиент Григорьев','client3','client3',4),
(12,'Клиент Дмитриева','client4','client4',4),
(13,'Клиент Егоров','client5','client5',4),
(14,'Клиент Жукова','client6','client6',4),
(15,'Клиент Зайцев','client7','client7',4),
(16,'Клиент Ильина','client8','client8',4),
(17,'Клиент Ковалев','client9','client9',4),
(18,'Клиент Лебедева','client10','client10',4),
(19,'Клиент Морозов','client11','client11',4),
(20,'Клиент Новикова','client12','client12',4),
(21,'Клиент Павлов','client13','client13',4),
(22,'Клиент Романова','client14','client14',4);

INSERT INTO public."Services" ("Id","Name","Description","Price") OVERRIDING SYSTEM VALUE VALUES
(1,'Замена масла','Замена моторного масла и фильтра',2500),
(2,'Диагностика','Компьютерная диагностика',1500),
(3,'Замена колодок','Замена тормозных колодок',4000),
(4,'Шиномонтаж','Снятие/установка и балансировка',2000),
(5,'Развал-схождение','Регулировка углов установки колес',3500),
(6,'Замена свечей','Замена свечей зажигания',1800),
(7,'Замена АКБ','Установка нового аккумулятора',1200),
(8,'Промывка инжектора','Чистка топливной системы',4500),
(9,'Замена ремня ГРМ','Комплект ГРМ с работой',12000),
(10,'Кондиционер','Заправка и диагностика кондиционера',3000),
(11,'Замена амортизаторов','Передняя пара амортизаторов',7000),
(12,'Полировка','Полировка кузова',5000),
(13,'Химчистка салона','Полная химчистка',6000),
(14,'Замена сцепления','Сцепление МКПП',15000),
(15,'Тормозная жидкость','Замена тормозной жидкости',2200),
(16,'Антифриз','Замена охлаждающей жидкости',2100),
(17,'Фильтр салона','Замена салонного фильтра',900),
(18,'Сход-развал 3D','3D стенд',4000),
(19,'Мойка двигателя','Бесконтактная мойка ДВС',1500),
(20,'Эвакуатор-прием','Прием авто с эвакуатора',1000);

INSERT INTO public."UserServices" ("Id","UserId","ServiceId") OVERRIDING SYSTEM VALUE VALUES
(1,4,1),(2,4,2),(3,4,3),(4,4,6),(5,4,15),
(6,5,2),(7,5,4),(8,5,5),(9,5,18),(10,5,10),
(11,6,1),(12,6,7),(13,6,8),(14,6,16),(15,6,17),
(16,7,3),(17,7,9),(18,7,11),(19,7,14),(20,7,15),
(21,8,4),(22,8,5),(23,8,12),(24,8,13),(25,8,20);

INSERT INTO public."Suppliers" ("Id","Name","Phone") OVERRIDING SYSTEM VALUE VALUES
(1,'АвтоДеталь','+7-900-111-22-01'),
(2,'ЗапЧастьПро','+7-900-111-22-02'),
(3,'МоторТрейд','+7-900-111-22-03'),
(4,'ШинаМаркет','+7-900-111-22-04'),
(5,'ЭлектроАвто','+7-900-111-22-05'),
(6,'КузовСервис','+7-900-111-22-06'),
(7,'ФильтрОпт','+7-900-111-22-07'),
(8,'МаслоОпт','+7-900-111-22-08'),
(9,'ТормозЦентр','+7-900-111-22-09'),
(10,'АмортизТорг','+7-900-111-22-10'),
(11,'АКБПлюс','+7-900-111-22-11'),
(12,'ГРМСнаб','+7-900-111-22-12'),
(13,'КлиматАвто','+7-900-111-22-13'),
(14,'ДетальЮг','+7-900-111-22-14'),
(15,'АвтоСевер','+7-900-111-22-15'),
(16,'ЗапСибирь','+7-900-111-22-16'),
(17,'ПрофиПартс','+7-900-111-22-17'),
(18,'ЕвроДеталь','+7-900-111-22-18'),
(19,'РусАвтоСнаб','+7-900-111-22-19'),
(20,'СервисПартс','+7-900-111-22-20');

INSERT INTO public."Parts" ("Id","Article","Name","Quantity","PurchasePrice","SalePrice","SupplierId") OVERRIDING SYSTEM VALUE VALUES
(1,'OIL-5W30','Масло 5W-30',40,800,1200,8),
(2,'FLT-001','Масляный фильтр',35,300,500,7),
(3,'BRK-FR','Колодки передние',20,1500,2500,9),
(4,'BRK-RR','Колодки задние',18,1400,2300,9),
(5,'TIRE-R','Ремкомплект шины',12,400,700,4),
(6,'SPK-NGK','Свечи NGK',50,250,450,3),
(7,'BAT-60','АКБ 60Ач',10,5500,7500,11),
(8,'GRM-KIT','Комплект ГРМ',8,6500,9000,12),
(9,'AMR-FL','Амортизатор передний',14,3200,4800,10),
(10,'FLT-CAB','Фильтр салона',40,350,600,7),
(11,'ANT-G12','Антифриз G12',25,600,950,8),
(12,'BRK-FLD','Тормозная жидкость DOT4',30,450,700,9),
(13,'AIR-FLT','Воздушный фильтр',28,400,650,7),
(14,'WIP-FR','Дворники передние',22,500,850,5),
(15,'BULB-H7','Лампа H7',60,150,280,5),
(16,'CLUTCH','Комплект сцепления',6,9000,13000,3),
(17,'AC-GAS','Фреон R134a',15,1200,2000,13),
(18,'BELT-ALT','Ремень генератора',16,700,1100,3),
(19,'OIL-0W20','Масло 0W-20',30,900,1400,8),
(20,'PAD-CER','Колодки керамика',10,2200,3400,9);

INSERT INTO public."Cars" ("Id","VIN","Brand","Model","Year","PlateNumber","Mileage","ClientId") OVERRIDING SYSTEM VALUE VALUES
(1,'XTA00000000000001','Lada','Vesta',2020,'A101AA777',45000,9),
(2,'XTA00000000000002','Toyota','Camry',2018,'B202BB199',98000,10),
(3,'XTA00000000000003','Kia','Rio',2019,'C303CC777',62000,11),
(4,'XTA00000000000004','Hyundai','Solaris',2021,'D404DD199',31000,12),
(5,'XTA00000000000005','VW','Polo',2017,'E505EE777',120000,13),
(6,'XTA00000000000006','Skoda','Rapid',2020,'F606FF199',54000,14),
(7,'XTA00000000000007','Renault','Logan',2016,'H707HH777',140000,15),
(8,'XTA00000000000008','Nissan','Qashqai',2019,'K808KK199',78000,16),
(9,'XTA00000000000009','Mazda','CX-5',2022,'M909MM777',22000,17),
(10,'XTA00000000000010','BMW','320i',2015,'O010OO199',160000,18),
(11,'XTA00000000000011','Audi','A4',2018,'P111PP777',89000,19),
(12,'XTA00000000000012','Ford','Focus',2014,'T212TT199',175000,20),
(13,'XTA00000000000013','Chevrolet','Cruze',2017,'U313UU777',110000,21),
(14,'XTA00000000000014','Honda','Civic',2020,'X414XX199',48000,22),
(15,'XTA00000000000015','Lada','Granta',2021,'Y515YY777',27000,9),
(16,'XTA00000000000016','Toyota','RAV4',2019,'A616AA199',72000,10),
(17,'XTA00000000000017','Kia','Sportage',2022,'B717BB777',19000,11),
(18,'XTA00000000000018','Hyundai','Creta',2020,'C818CC199',56000,12),
(19,'XTA00000000000019','VW','Tiguan',2018,'D919DD777',95000,13),
(20,'XTA00000000000020','Skoda','Octavia',2021,'E020EE199',34000,14);

INSERT INTO public."Orders" ("Id","DateCreated","DateFinished","StatusId","AutomobileId","MechanicId") OVERRIDING SYSTEM VALUE VALUES
(1, TIMESTAMPTZ '2026-10-01 09:00:00+03', TIMESTAMPTZ '2026-10-01 12:00:00+03', 3, 1, 4),
(2, TIMESTAMPTZ '2026-10-02 10:00:00+03', NULL, 2, 2, 5),
(3, TIMESTAMPTZ '2026-10-03 11:00:00+03', NULL, 1, 3, 6),
(4, TIMESTAMPTZ '2026-10-03 14:00:00+03', TIMESTAMPTZ '2026-10-03 17:00:00+03', 3, 4, 4),
(5, TIMESTAMPTZ '2026-10-04 09:30:00+03', NULL, 2, 5, 7),
(6, TIMESTAMPTZ '2026-10-04 15:00:00+03', NULL, 1, 6, 5),
(7, TIMESTAMPTZ '2026-10-05 08:00:00+03', TIMESTAMPTZ '2026-10-05 11:00:00+03', 3, 7, 8),
(8, TIMESTAMPTZ '2026-10-05 13:00:00+03', NULL, 2, 8, 4),
(9, TIMESTAMPTZ '2026-10-06 09:00:00+03', NULL, 1, 9, 6),
(10, TIMESTAMPTZ '2026-10-06 16:00:00+03', TIMESTAMPTZ '2026-10-06 18:00:00+03', 3, 10, 7),
(11, TIMESTAMPTZ '2026-10-07 10:00:00+03', NULL, 2, 11, 5),
(12, TIMESTAMPTZ '2026-10-07 14:30:00+03', NULL, 1, 12, 8),
(13, TIMESTAMPTZ '2026-10-08 09:00:00+03', TIMESTAMPTZ '2026-10-08 13:00:00+03', 3, 13, 4),
(14, TIMESTAMPTZ '2026-10-08 15:00:00+03', NULL, 2, 14, 6),
(15, TIMESTAMPTZ '2026-10-09 08:30:00+03', NULL, 1, 15, 7),
(16, TIMESTAMPTZ '2026-10-09 12:00:00+03', TIMESTAMPTZ '2026-10-09 15:00:00+03', 3, 16, 5),
(17, TIMESTAMPTZ '2026-10-10 09:00:00+03', NULL, 2, 17, 8),
(18, TIMESTAMPTZ '2026-10-10 11:00:00+03', NULL, 1, 18, 4),
(19, TIMESTAMPTZ '2026-10-10 14:00:00+03', NULL, 4, 19, 6),
(20, TIMESTAMPTZ '2026-10-10 16:00:00+03', NULL, 2, 20, 7);

INSERT INTO public."OrderServices" ("Id","OrderId","ServiceId","ActualPrice","IsCompleted") OVERRIDING SYSTEM VALUE VALUES
(1,1,1,2500,true),(2,1,2,1500,true),
(3,2,4,2000,false),(4,2,5,3500,false),
(5,3,2,1500,false),
(6,4,3,4000,true),
(7,5,9,12000,false),
(8,6,10,3000,false),
(9,7,4,2000,true),(10,7,18,4000,true),
(11,8,1,2500,false),
(12,9,7,1200,false),
(13,10,11,7000,true),
(14,11,5,3500,false),
(15,12,12,5000,false),
(16,13,6,1800,true),(17,13,17,900,true),
(18,14,8,4500,false),
(19,15,16,2100,false),
(20,16,15,2200,true),
(21,17,13,6000,false),
(22,18,1,2500,false),
(23,19,20,1000,false),
(24,20,3,4000,false);

INSERT INTO public."OrderParts" ("Id","OrderId","PartId","Quantity") OVERRIDING SYSTEM VALUE VALUES
(1,1,1,4),(2,1,2,1),
(3,2,5,1),
(4,4,3,1),
(5,5,8,1),
(6,7,5,2),
(7,8,1,4),(8,8,2,1),
(9,10,9,2),
(10,11,10,1),
(11,13,6,4),(12,13,10,1),
(13,14,13,1),
(14,15,11,2),
(15,16,12,1),
(16,17,14,1),
(17,18,19,4),
(18,19,15,2),
(19,20,3,1),(20,20,4,1);

INSERT INTO public."Payments" ("Id","OrderId","Amount","Method") OVERRIDING SYSTEM VALUE VALUES
(1,1,5200,'Карта'),
(2,4,6500,'Наличные'),
(3,7,6000,'Карта'),
(4,10,9600,'Карта'),
(5,13,3600,'Перевод'),
(6,16,2200,'Наличные'),
(7,1,500,'Наличные'),
(8,2,2000,'Карта'),
(9,5,5000,'Карта'),
(10,8,1500,'Наличные'),
(11,11,1000,'Карта'),
(12,14,2000,'Перевод'),
(13,17,3000,'Карта'),
(14,18,1000,'Наличные'),
(15,20,2500,'Карта'),
(16,3,500,'Наличные'),
(17,6,1000,'Карта'),
(18,9,600,'Наличные'),
(19,12,1500,'Перевод'),
(20,15,800,'Карта');

INSERT INTO public."Comments" ("Id","OrderId","Text","CreatedAt","IsFinalClientReview") OVERRIDING SYSTEM VALUE VALUES
(1,1,'Масло заменено, фильтр новый', TIMESTAMPTZ '2026-10-01 11:00:00+03', false),
(2,1,'Все отлично, спасибо!', TIMESTAMPTZ '2026-10-01 12:30:00+03', true),
(3,2,'Ждем резину со склада', TIMESTAMPTZ '2026-10-02 11:00:00+03', false),
(4,4,'Колодки заменены', TIMESTAMPTZ '2026-10-03 16:00:00+03', false),
(5,4,'Быстро и качественно', TIMESTAMPTZ '2026-10-03 17:30:00+03', true),
(6,5,'Нужен комплект ГРМ', TIMESTAMPTZ '2026-10-04 10:00:00+03', false),
(7,7,'Балансировка выполнена', TIMESTAMPTZ '2026-10-05 10:30:00+03', false),
(8,7,'Рекомендую сервис', TIMESTAMPTZ '2026-10-05 11:30:00+03', true),
(9,8,'Проверить уровень масла', TIMESTAMPTZ '2026-10-05 14:00:00+03', false),
(10,10,'Амортизаторы установлены', TIMESTAMPTZ '2026-10-06 17:00:00+03', false),
(11,10,'Машина стала мягче ехать', TIMESTAMPTZ '2026-10-06 18:30:00+03', true),
(12,11,'Клиент просит срочно', TIMESTAMPTZ '2026-10-07 10:30:00+03', false),
(13,13,'Свечи и фильтр салона заменены', TIMESTAMPTZ '2026-10-08 12:00:00+03', false),
(14,13,'Супер сервис', TIMESTAMPTZ '2026-10-08 13:30:00+03', true),
(15,14,'Промывка в процессе', TIMESTAMPTZ '2026-10-08 16:00:00+03', false),
(16,16,'ТО выполнено', TIMESTAMPTZ '2026-10-09 14:00:00+03', false),
(17,16,'Спасибо мастеру', TIMESTAMPTZ '2026-10-09 15:30:00+03', true),
(18,17,'Запись на химчистку', TIMESTAMPTZ '2026-10-10 09:30:00+03', false),
(19,19,'Клиент отменил визит', TIMESTAMPTZ '2026-10-10 14:30:00+03', false),
(20,20,'Не хватает колодок на складе', TIMESTAMPTZ '2026-10-10 16:30:00+03', false);

INSERT INTO public."Shifts" ("Id","Name","DayOfWeek","UserId") OVERRIDING SYSTEM VALUE VALUES
(1,'Утро','Пн',4),(2,'Вечер','Пн',5),
(3,'Утро','Вт',6),(4,'Вечер','Вт',7),
(5,'Утро','Ср',8),(6,'Вечер','Ср',4),
(7,'Утро','Чт',5),(8,'Вечер','Чт',6),
(9,'Утро','Пт',7),(10,'Вечер','Пт',8),
(11,'Утро','Пн',6),(12,'Вечер','Вт',8),
(13,'Утро','Ср',5),(14,'Вечер','Чт',4),
(15,'Утро','Пт',4),(16,'Вечер','Пн',7),
(17,'Утро','Вт',4),(18,'Вечер','Ср',7),
(19,'Утро','Чт',8),(20,'Вечер','Пт',5);

INSERT INTO public."PartRequests" ("Id","ItemName","Quantity","Note","UserId","CreatedAt") OVERRIDING SYSTEM VALUE VALUES
(1,'Ключ динамометрический',1,'Для ГРМ',4, TIMESTAMPTZ '2026-10-04 10:00:00+03'),
(2,'Колодки керамика',2,'Под заказ',7, TIMESTAMPTZ '2026-10-05 09:00:00+03'),
(3,'Фреон R134a',3,'Кондиционер',5, TIMESTAMPTZ '2026-10-06 11:00:00+03'),
(4,'Комплект сцепления',1,'Logan',8, TIMESTAMPTZ '2026-10-07 12:00:00+03'),
(5,'Масляный фильтр FLT-001',10,'Запас',4, TIMESTAMPTZ '2026-10-07 15:00:00+03'),
(6,'Амортизатор передний',2,'CX-5',7, TIMESTAMPTZ '2026-10-08 09:00:00+03'),
(7,'Свечи NGK',8,'Camry',6, TIMESTAMPTZ '2026-10-08 10:00:00+03'),
(8,'Антифриз G12',5,'Creta',6, TIMESTAMPTZ '2026-10-09 08:00:00+03'),
(9,'Ремень генератора',2,'Focus',8, TIMESTAMPTZ '2026-10-09 11:00:00+03'),
(10,'Лампа H7',20,'Склад',5, TIMESTAMPTZ '2026-10-09 13:00:00+03'),
(11,'Масло 0W-20',6,'RAV4',4, TIMESTAMPTZ '2026-10-09 14:00:00+03'),
(12,'Фильтр салона',15,'Опт',5, TIMESTAMPTZ '2026-10-09 16:00:00+03'),
(13,'Тормозная жидкость',4,'Sportage',7, TIMESTAMPTZ '2026-10-10 08:00:00+03'),
(14,'Воздушный фильтр',5,'Octavia',4, TIMESTAMPTZ '2026-10-10 09:00:00+03'),
(15,'Дворники',2,'Tiguan',8, TIMESTAMPTZ '2026-10-10 10:00:00+03'),
(16,'Комплект ГРМ',1,'Cruze',7, TIMESTAMPTZ '2026-10-10 11:00:00+03'),
(17,'АКБ 60Ач',1,'Granta',6, TIMESTAMPTZ '2026-10-10 12:00:00+03'),
(18,'Колодки задние',2,'Polo',4, TIMESTAMPTZ '2026-10-10 13:00:00+03'),
(19,'Ремкомплект шины',3,'Сезон',5, TIMESTAMPTZ '2026-10-10 14:00:00+03'),
(20,'Масло 5W-30',12,'Склад',8, TIMESTAMPTZ '2026-10-10 15:00:00+03');

SELECT setval(pg_get_serial_sequence('public."Roles"', 'Id'), (SELECT MAX("Id") FROM public."Roles"));
SELECT setval(pg_get_serial_sequence('public."Statuses"', 'Id'), (SELECT MAX("Id") FROM public."Statuses"));
SELECT setval(pg_get_serial_sequence('public."Users"', 'Id'), (SELECT MAX("Id") FROM public."Users"));
SELECT setval(pg_get_serial_sequence('public."Services"', 'Id'), (SELECT MAX("Id") FROM public."Services"));
SELECT setval(pg_get_serial_sequence('public."UserServices"', 'Id'), (SELECT MAX("Id") FROM public."UserServices"));
SELECT setval(pg_get_serial_sequence('public."Suppliers"', 'Id'), (SELECT MAX("Id") FROM public."Suppliers"));
SELECT setval(pg_get_serial_sequence('public."Parts"', 'Id'), (SELECT MAX("Id") FROM public."Parts"));
SELECT setval(pg_get_serial_sequence('public."Cars"', 'Id'), (SELECT MAX("Id") FROM public."Cars"));
SELECT setval(pg_get_serial_sequence('public."Orders"', 'Id'), (SELECT MAX("Id") FROM public."Orders"));
SELECT setval(pg_get_serial_sequence('public."OrderServices"', 'Id'), (SELECT MAX("Id") FROM public."OrderServices"));
SELECT setval(pg_get_serial_sequence('public."OrderParts"', 'Id'), (SELECT MAX("Id") FROM public."OrderParts"));
SELECT setval(pg_get_serial_sequence('public."Payments"', 'Id'), (SELECT MAX("Id") FROM public."Payments"));
SELECT setval(pg_get_serial_sequence('public."Comments"', 'Id'), (SELECT MAX("Id") FROM public."Comments"));
SELECT setval(pg_get_serial_sequence('public."Shifts"', 'Id'), (SELECT MAX("Id") FROM public."Shifts"));
SELECT setval(pg_get_serial_sequence('public."PartRequests"', 'Id'), (SELECT MAX("Id") FROM public."PartRequests"));

COMMIT;
