-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Cars"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "VIN" text COLLATE pg_catalog."default" NOT NULL,
    "Brand" text COLLATE pg_catalog."default" NOT NULL,
    "Model" text COLLATE pg_catalog."default" NOT NULL,
    "Year" integer NOT NULL,
    "PlateNumber" text COLLATE pg_catalog."default" NOT NULL,
    "Mileage" integer NOT NULL,
    "ClientId" integer NOT NULL,
    CONSTRAINT "PK_Cars" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Comments"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "OrderId" integer NOT NULL,
    "Text" text COLLATE pg_catalog."default" NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Comments" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."OrderParts"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "OrderId" integer NOT NULL,
    "PartId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    CONSTRAINT "PK_OrderParts" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."OrderServices"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "OrderId" integer NOT NULL,
    "ServiceId" integer NOT NULL,
    "ActualPrice" numeric NOT NULL,
    CONSTRAINT "PK_OrderServices" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Orders"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "DateCreated" timestamp with time zone NOT NULL,
    "DateFinished" timestamp with time zone,
    "StatusId" integer NOT NULL,
    "AutomobileId" integer NOT NULL,
    "MechanicId" integer NOT NULL,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Parts"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Article" text COLLATE pg_catalog."default" NOT NULL,
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "Quantity" integer NOT NULL,
    "PurchasePrice" numeric NOT NULL,
    "SalePrice" numeric NOT NULL,
    "SupplierId" integer NOT NULL,
    CONSTRAINT "PK_Parts" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Payments"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "OrderId" integer NOT NULL,
    "Amount" numeric NOT NULL,
    "Method" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Payments" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Roles"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Services"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default",
    "Price" numeric NOT NULL,
    CONSTRAINT "PK_Services" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Shifts"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "DayOfWeek" text COLLATE pg_catalog."default" NOT NULL,
    "UserId" integer,
    CONSTRAINT "PK_Shifts" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Statuses"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Statuses" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Suppliers"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "Phone" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Suppliers" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."UserServices"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" integer NOT NULL,
    "ServiceId" integer NOT NULL,
    CONSTRAINT "PK_UserServices" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Users"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "Login" text COLLATE pg_catalog."default" NOT NULL,
    "Password" text COLLATE pg_catalog."default" NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory"
(
    "MigrationId" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "ProductVersion" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);
END;